version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid:
    image: aerokube/selenoid:latest-release
    command: -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video -log-output-dir /opt/selenoid/logs
    network_mode: bridge
    ports:
      - 5656:4444
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: /opt/selenoid/video
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/video:/opt/selenoid/video
      - ./selenoid/logs:/opt/selenoid/logs
      - ./selenoid/browsers.json:/etc/selenoid/browsers.json:ro

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    command: --selenoid-uri http://selenoid:4444
    network_mode: bridge
    ports:
      - 5599:8000